// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace elizor.ecommerce.user.dbcontext.tables
{
    public partial class eep_t_customer
    {
        public string Id { get; set; }
        public string EEP_T_TitleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string EmailAddress { get; set; }
        public string TelNo { get; set; }
        public string EEP_T_ClientId { get; set; }
        public sbyte Status { get; set; }
        public sbyte ReceivePromotionOffers { get; set; }
        public sbyte AgreeTermsConditions { get; set; }
        public string PromotionChannel { get; set; }
        public string HearAbout { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? Birthday { get; set; }

        public virtual eep_t_client EEP_T_Client { get; set; }
    }
}