// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace elizor.ecommerce.user.dbcontext.tables
{
    public partial class eep_t_client
    {
        public eep_t_client()
        {
            eep_t_customer = new HashSet<eep_t_customer>();
        }

        public string Id { get; set; }
        public string ClientName { get; set; }
        public string ClientDetails { get; set; }
        public string EEP_T_CurrencyId { get; set; }
        public sbyte Status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }

        public virtual eep_t_currency EEP_T_Currency { get; set; }
        public virtual ICollection<eep_t_customer> eep_t_customer { get; set; }
    }
}