// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace elizor.ecommerce.user.dbcontext.tables
{
    public partial class Myguests
    {
        public uint Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public DateTime? RegDate { get; set; }
    }
}